### ISSUE TITLE
.NET Framework?

### ISSUE THREAD

**Issue by astrohart** [ByronAP/CoinCapApi#15]
The NuGet package won't install in my project.  I am working on a .NET Framework 4.8 class library.  Is there a way to make it support the .NET Framework?  Thanks.

**Comment by ByronAP** [comment]
Since this library is NET Standard, so it won't work. I will make a build for .NET framework tomorrow though.

**Comment by astrohart** [comment]
@ByronAP thanks for the fast response!  Greatly appreciated!  -- P.S. Please do so also with the `ByronAP.Net.WebSockets` NuGet package as well, if you would be so very kind :-)

**Comment by ByronAP** [comment]
That library will take a bit longer

**Comment by ByronAP** [comment]
yup ok I forgot websockets was a dependancy so I would need to change that as well for full functionality. #my_bad

**Comment by ByronAP** [comment]
OK I got websockets out of the way, not as bad as I thought it would be, new package is 0.8.1.1 in nuget

**Comment by ByronAP** [comment]
released as version 2.0.2.1

**Comment by astrohart** [comment]
@ByronAP Really appreciate the help with making it compatible with .NET Framework!  Thanks for the time #kudos
